language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 4
  - 6
  - 8
after_success:
  - npm install -g semantic-release
  - npm install --no-save semantic-release-tamia
  - semantic-release --analyze-commits semantic-release-tamia/analyzeCommits --verify-release semantic-release-tamia/verifyRelease --generate-notes semantic-release-tamia/generateNotes
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
